spring.application.name=lab4

spring.datasource.url=jdbc:postgresql://localhost:5432/web_db
spring.datasource.username=postgres
spring.datasource.password=5432

testing.app.jwtSecret=SuperSecretKeyForLab4ThatShouldBeVeryLongAndComplex123456
testing.app.jwtExpirationMs=86400000

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true